ValueSet: BRCID10MetabolicoVS
Id: cid10-metabolico-vs
Title: "CID-10 Diagnósticos Metabólicos ValueSet"
Description: "Subconjunto de códigos CID-10 para diagnósticos metabólicos comumente associados a exames laboratoriais. Inclui diabetes mellitus, dislipidemias, obesidade e distúrbios da tireoide."
* ^copyright = "Os direitos de publicação e distribuição da CID-10 em português pertencem à Edusp - Editora da Universidade de São Paulo. Os arquivos eletrônicos elaborados pelo CBCD podem ser utilizados livremente em instalações de usuários e por desenvolvedores de sistemas, desde que sejam dados os devidos créditos e não seja cobrado pelo seu uso."

// Diabetes mellitus
* $ICD10#E10 "Diabetes mellitus insulino-dependente"
* $ICD10#E10.0 "Diabetes mellitus insulino-dependente — com coma"
* $ICD10#E10.1 "Diabetes mellitus insulino-dependente — com cetoacidose"
* $ICD10#E10.2 "Diabetes mellitus insulino-dependente — com complicações renais"
* $ICD10#E10.3 "Diabetes mellitus insulino-dependente — com complicações oftálmicas"
* $ICD10#E10.4 "Diabetes mellitus insulino-dependente — com complicações neurológicas"
* $ICD10#E10.5 "Diabetes mellitus insulino-dependente — com complicações circulatórias periféricas"
* $ICD10#E10.6 "Diabetes mellitus insulino-dependente — com outras complicações especificadas"
* $ICD10#E10.7 "Diabetes mellitus insulino-dependente — com complicações múltiplas"
* $ICD10#E10.8 "Diabetes mellitus insulino-dependente — com complicações não especificadas"
* $ICD10#E10.9 "Diabetes mellitus insulino-dependente — sem complicações"
* $ICD10#E11 "Diabetes mellitus não insulino-dependente"
* $ICD10#E11.0 "Diabetes mellitus não insulino-dependente — com coma"
* $ICD10#E11.1 "Diabetes mellitus não insulino-dependente — com cetoacidose"
* $ICD10#E11.2 "Diabetes mellitus não insulino-dependente — com complicações renais"
* $ICD10#E11.3 "Diabetes mellitus não insulino-dependente — com complicações oftálmicas"
* $ICD10#E11.4 "Diabetes mellitus não insulino-dependente — com complicações neurológicas"
* $ICD10#E11.5 "Diabetes mellitus não insulino-dependente — com complicações circulatórias periféricas"
* $ICD10#E11.6 "Diabetes mellitus não insulino-dependente — com outras complicações especificadas"
* $ICD10#E11.7 "Diabetes mellitus não insulino-dependente — com complicações múltiplas"
* $ICD10#E11.8 "Diabetes mellitus não insulino-dependente — com complicações não especificadas"
* $ICD10#E11.9 "Diabetes mellitus não insulino-dependente — sem complicações"
* $ICD10#E13 "Outros tipos especificados de diabetes mellitus"
* $ICD10#E14 "Diabetes mellitus não especificado"

// Distúrbios do metabolismo de lipoproteínas
* $ICD10#E78 "Distúrbios do metabolismo de lipoproteínas e outras lipidemias"
* $ICD10#E78.0 "Hipercolesterolemia pura"
* $ICD10#E78.1 "Hipertrigliceridemia pura"
* $ICD10#E78.2 "Hiperlipidemia mista"
* $ICD10#E78.3 "Hiperquilomicronemia"
* $ICD10#E78.4 "Outras hiperlipidemias"
* $ICD10#E78.5 "Hiperlipidemia não especificada"
* $ICD10#E78.6 "Deficiências de lipoproteínas"
* $ICD10#E78.8 "Outros distúrbios do metabolismo de lipoproteínas"
* $ICD10#E78.9 "Distúrbio não especificado do metabolismo de lipoproteínas"

// Obesidade e hiperalimentação
* $ICD10#E66 "Obesidade"
* $ICD10#E66.0 "Obesidade devida a excesso de calorias"
* $ICD10#E66.1 "Obesidade induzida por drogas"
* $ICD10#E66.2 "Obesidade extrema com hipoventilação alveolar"
* $ICD10#E66.8 "Outra obesidade"
* $ICD10#E66.9 "Obesidade não especificada"

// Distúrbios da tireoide
* $ICD10#E01 "Doenças tireoidianas relacionadas à deficiência de iodo e afecções associadas"
* $ICD10#E02 "Hipotireoidismo subclínico por deficiência de iodo"
* $ICD10#E03 "Outro hipotireoidismo"
* $ICD10#E03.0 "Hipotireoidismo congênito com bócio difuso"
* $ICD10#E03.1 "Hipotireoidismo congênito sem bócio"
* $ICD10#E03.8 "Outro hipotireoidismo especificado"
* $ICD10#E03.9 "Hipotireoidismo não especificado"
* $ICD10#E05 "Tireotoxicose (hipertireoidismo)"
* $ICD10#E05.0 "Tireotoxicose com bócio difuso"
* $ICD10#E05.9 "Tireotoxicose não especificada"
* $ICD10#E06 "Tireoidite"
* $ICD10#E06.3 "Tireoidite autoimune"

// Hiperuricemia e gota
* $ICD10#E79 "Distúrbios do metabolismo de purina e pirimidina"
* $ICD10#E79.0 "Hiperuricemia sem sinais de artrite inflamatória e de doença tofácea"
* $ICD10#M10 "Gota"
* $ICD10#M10.0 "Gota idiopática"
* $ICD10#M10.9 "Gota não especificada"

// Deficiências vitamínicas
* $ICD10#E53 "Deficiência de outras vitaminas do grupo B"
* $ICD10#E53.8 "Deficiência de outras vitaminas especificadas do grupo B"
* $ICD10#E55 "Deficiência de vitamina D"
* $ICD10#E55.0 "Raquitismo ativo"
* $ICD10#E55.9 "Deficiência não especificada de vitamina D"
* $ICD10#E56 "Outras deficiências vitamínicas"
* $ICD10#E61 "Deficiência de outros elementos nutrientes"
* $ICD10#E61.1 "Deficiência de ferro"

// Anemias nutricionais
* $ICD10#D50 "Anemia por deficiência de ferro"
* $ICD10#D50.0 "Anemia por deficiência de ferro secundária a perda de sangue (crônica)"
* $ICD10#D50.8 "Outras anemias por deficiência de ferro"
* $ICD10#D50.9 "Anemia por deficiência de ferro não especificada"
* $ICD10#D51 "Anemia por deficiência de vitamina B12"
* $ICD10#D51.0 "Anemia por deficiência de vitamina B12 devida a deficiência de fator intrínseco"
* $ICD10#D51.9 "Anemia por deficiência de vitamina B12 não especificada"
* $ICD10#D52 "Anemia por deficiência de folato"
* $ICD10#D52.9 "Anemia por deficiência de folato não especificada"
