CodeSystem: BRCNESCS
Id: cnes-tipo-estabelecimento
Title: "CNES — Tipos de Estabelecimento de Saúde"
Description: "Tipos de estabelecimento de saúde conforme o Cadastro Nacional de Estabelecimentos de Saúde (CNES), mantido pelo DATASUS/Ministério da Saúde."
* ^url = "https://fhir-brasil.dev.br/CodeSystem/cnes-tipo-estabelecimento"
* ^status = #active
* ^content = #complete
* ^caseSensitive = true
* ^publisher = "DATASUS / Ministério da Saúde"
* #01 "Posto de Saúde"
* #02 "Centro de Saúde / Unidade Básica de Saúde"
* #04 "Policlínica"
* #05 "Hospital Geral"
* #07 "Hospital Especializado"
* #09 "Pronto Atendimento"
* #15 "Unidade Mista"
* #20 "Pronto Socorro Geral"
* #21 "Pronto Socorro Especializado"
* #22 "Consultório Isolado"
* #36 "Clínica / Centro de Especialidade"
* #39 "Unidade de Apoio Diagnose e Terapia (SADT Isolado)"
* #40 "Unidade Móvel Terrestre"
* #42 "Unidade Móvel de Nível Pré-Hospitalar — Urgência / Emergência"
* #43 "Farmácia"
* #50 "Unidade de Vigilância em Saúde"
* #60 "Cooperativa ou Empresa de Cessão de Trabalhadores na Saúde"
* #61 "Centro de Parto Normal — Isolado"
* #62 "Hospital-Dia — Isolado"
* #64 "Central de Regulação de Serviços de Saúde"
* #67 "Laboratório Central de Saúde Pública (LACEN)"
* #68 "Central de Gestão em Saúde"
* #69 "Centro de Atenção Hemoterapia e/ou Hematológica"
* #70 "Centro de Atenção Psicossocial"
* #71 "Centro de Apoio à Saúde da Família"
* #72 "Unidade de Atenção à Saúde Indígena"
* #73 "Polo de Prevenção de Doenças e Agravos e Promoção da Saúde"
* #74 "Polo Academia da Saúde"
* #76 "Central de Regulação Médica de Urgências"
* #79 "Oficina Ortopédica"
* #80 "Laboratório de Saúde Pública"
* #81 "Central de Abastecimento"
* #82 "Unidade de Atenção em Regime Residencial"
* #83 "Polo de Prevenção de Doenças e Agravos de Saúde Bucal"
* #85 "Centro de Imunobiológicos Especiais"
